######################################################################
# Automatically generated by qmake (3.0) ?? ???. 24 04:13:44 2017
######################################################################
QT += core gui charts
CONFIG += c++11
TEMPLATE = app
TARGET = job_test
INCLUDEPATH += .

# Input
HEADERS += chartview.h
SOURCES += chartview.cpp main.cpp
